version: 2.1
description: A builder orb.
jobs:
  deploy:
    parameters:
      bucket:
        type: string
      artifact_schema:
        type: string
        default: "default"
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            git clone ${CIRCLE_REPOSITORY_URL}
            cd ${CIRCLE_PROJECT_REPONAME}
            version=${CIRCLE_BUILD_NUM}-${CIRCLE_BRANCH}
            cd ..
            mkdir root
            cd root
            mkdir -p artifacts/$version
            cat >${CIRCLE_BRANCH}.version \<<EOF
            $version
            EOF
            cat >artifacts/$version/manifest.json \<<EOF
            {
                "artifactSchema": "<< parameters.artifact_schema >>",
                "version": "$version",
                "commitHash": "${CIRCLE_SHA1}"
            }
            EOF
            aws s3 sync . s3://<< parameters.bucket >>/packages/${CIRCLE_PROJECT_REPONAME}/