version: 2.1
description: A builder orb.
jobs:
  publish-github-release:
    description: Publish a new release tagged `vX.Y.Z`.
    parameters:
      tag:
        type: string
    docker:
      - image: cibuilds/github:0.10
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          command: |
            # TODO: PATH is required by ghr command, so let's just arbitrarily set it to ./.circleci since that folder should exist
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete << parameters.tag >> ./.circleci
  deploy:
    parameters:
      bucket:
        type: string
      artifact_schema:
        type: string
        default: "default"
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            git clone ${CIRCLE_REPOSITORY_URL}
            cd ${CIRCLE_PROJECT_REPONAME}
            version=`git describe --exact-match --tags ${CIRCLE_SHA1}`
            cd ..
            mkdir root
            cd root
            mkdir -p artifacts/$version
            cat >${CIRCLE_BRANCH}.version \<<EOF
            $version
            EOF
            cat >artifacts/$version/manifest.json \<<EOF
            {
                "artifactSchema": "<< parameters.artifact_schema >>",
                "version": "$version",
                "commitHash": "${CIRCLE_SHA1}"
            }
            EOF
            aws s3 sync . s3://<< parameters.bucket >>/packages/${CIRCLE_PROJECT_REPONAME}/