# TODO: Use Git Clone to bring shell scripts locally
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publishes Release on GitHub"
          command: |
            ghr -t 46afc935c6aa7d8f32425a1aab97c7f4f323bf394 -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./artifacts/
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          name: Deploy
          command: chmod -R +x ./devops & ./devops/release.sh

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
      - deploy:
          requires:
            - build