# TODO: Use orbs
# TODO: Create new github privately and perform steps again, recording them
version: 2.1
orbs:
  builder: dsc_tests/builder@dev:first
workflows:
  version: 2
  main:
    jobs:
      - builder/publish-github-release:
          filters:
            branches:
              only: master
      - builder/deploy:
          requires:
            - builder/publish-github-release