# TODO: Make sure it meets ticket requirements
# TODO: Create new github privately and perform steps again, recording them
# TODO: Document on Agora
# TODO: Documentation for orbs in files and orb page
# TODO: Test other branches
# TODO: Check for GITHUB_TOKEN
version: 2.1
orbs:
  builder: dsc_test/builder@dev:1.0.6
workflows:
  version: 2
  main:
    jobs:
      - builder/publish-github-release:
          tag: 6.7.0
          filters:
            branches:
              only: master
      - builder/deploy:
          bucket: davidchen
          requires:
            - builder/publish-github-release