# TODO: Document on Agora
# TODO: Documentation for orbs in files and orb page
# TODO: Checkin orb to FN repo
version: 2.1
orbs:
  builder: dsc_test/builder@dev:1.0.9
workflows:
  version: 2
  main:
    jobs:
      - builder/publish-github-release:
          filters:
            branches:
              only: master
      - builder/deploy:
          bucket: davidchen
          requires:
            - builder/publish-github-release