# TODO: Use Git Clone to bring shell scripts locally. Pass it to next jobs
# TODO: CHECK IF TAG IS EMPTY. Only deploy if master. Create tag in git if not exist. Tag commit too
# TODO: Use orbs
# TODO: Create new github privately and perform steps again, recording them
# TODO: Create tag programmatically?
# TODO: Get GHR token
# TODO: Only deploy on master
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - checkout
      - run:
          name: "Publishes Release on GitHub"
          command: ./devops/tag.sh
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          name: Deploy
          command: chmod -R +x ./devops && ./devops/release.sh

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
      - deploy:
          requires:
            - build