# TODO: Use Git Clone to bring shell scripts locally. Pass it to next jobs
# TODO: CHECK IF TAG IS EMPTY. Only deploy if master. Create tag in git if not exist. Tag commit too
# TODO: Use orbs
# TODO: Create new github privately and perform steps again, recording them
# TODO: Get GHR token
# TODO: Only deploy on master
version: 2.1
orbs:
  fn_orb:
    jobs:
      publish-github-release:
        description: Publish a new release tagged `vX.Y.Z`.
        docker:
          - image: cibuilds/github:0.10
        working_directory: ~/circle-tmp-folder
        steps:
          - checkout
          - run:
              command: |
                VERSION=`cat version_info`
                ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} .
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
          name: Deploy
          command: chmod -R +x ./devops && ./devops/release.sh
workflows:
  version: 2
  main:
    jobs:
      - build
      - fn_orb/publish-github-release:
          requires:
            - build
      - deploy:
          requires:
            - fn-orb/publish-github-release