# TODO: Use Git Clone to bring shell scripts locally. Pass it to next jobs
# TODO: CHECK IF TAG IS EMPTY. Only deploy if master. Create tag in git if not exist. Tag commit too
# TODO: Use orbs
# TODO: Create new github privately and perform steps again, recording them
# TODO: Create tag programmatically?
# TODO: Get GHR token
# TODO: Only deploy on master
version: 2.1
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
  publish-github-release:
    description: Create dummy file and publish a new release tagged `vX.Y.Z`.
    executor: github-release/default
    steps:
      - checkout
      - github-release/create:
          tag: 7.9.0
          title: Version 1.9.0
          description: This release is version 1.9.0 .h
  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout
      - run:
        name: Deploy
        command: chmod -R +x ./devops && ./devops/release.s

workflows:
  version: 2
  main:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
      - deploy:
          requires:
            - publish-github-release