# TODO: Make sure it meets ticket requirements
# TODO: Create new github privately and perform steps again, recording them
# TODO: combine publish and deploy, or pipe version to deploy?
# TODO: custom artifact
# TODO: Document on Agora
# TODO: Documentation for orbs in files and orb page
version: 2.1
orbs:
  builder: dsc_test/builder@dev:1.0.3
workflows:
  version: 2
  main:
    jobs:
      - builder/publish-github-release:
          filters:
            branches:
              only: master
      - builder/deploy:
          bucket: davidchen
          artifact_schema: "haha"
          requires:
            - builder/publish-github-release